-- Demand Optimization: Database Setup
CREATE DATABASE IF NOT EXISTS MANUFACTURING_DEMAND;

CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.RAW;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.CURATED;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.AI;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.ML;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.SEARCH;
CREATE SCHEMA IF NOT EXISTS MANUFACTURING_DEMAND.APP;

USE DATABASE MANUFACTURING_DEMAND;
USE WAREHOUSE CORTEX;
