-- Demand Optimization: Raw Tables
USE SCHEMA MANUFACTURING_DEMAND.RAW;

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,       -- Electronics, Automotive, Pharma, FMCG, Industrial
    SUB_CATEGORY VARCHAR,
    UNIT_COST NUMBER(10,2),
    LEAD_TIME_DAYS NUMBER,
    MIN_ORDER_QTY NUMBER,
    SUPPLIER VARCHAR
);

CREATE OR REPLACE TABLE WAREHOUSES (
    WAREHOUSE_ID VARCHAR,
    WAREHOUSE_NAME VARCHAR,
    REGION VARCHAR,
    COUNTRY VARCHAR,
    CAPACITY_UNITS NUMBER,
    OPERATING_COST_DAILY NUMBER(10,2)
);

CREATE OR REPLACE TABLE DEMAND_HISTORY (
    DEMAND_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    WAREHOUSE_ID VARCHAR,
    DEMAND_DATE DATE,
    ACTUAL_DEMAND NUMBER,
    FORECAST_DEMAND NUMBER,
    FORECAST_ERROR NUMBER(5,2),
    CHANNEL VARCHAR
);

CREATE OR REPLACE TABLE INVENTORY (
    INVENTORY_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    WAREHOUSE_ID VARCHAR,
    SNAPSHOT_DATE DATE,
    ON_HAND_QTY NUMBER,
    IN_TRANSIT_QTY NUMBER,
    ALLOCATED_QTY NUMBER,
    DAYS_OF_SUPPLY NUMBER(5,1),
    VALUE_AT_RISK NUMBER(12,2)
);

CREATE OR REPLACE TABLE PURCHASE_ORDERS (
    PO_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    WAREHOUSE_ID VARCHAR,
    ORDER_DATE DATE,
    QUANTITY NUMBER,
    ORDER_TYPE VARCHAR,     -- STANDARD, RUSH, EMERGENCY
    STATUS VARCHAR,
    SUPPLIER VARCHAR,
    EXPEDITE_COST NUMBER(10,2)
);

CREATE OR REPLACE TABLE PLANNING_DOCS (
    DOC_ID VARCHAR,
    TITLE VARCHAR,
    CATEGORY VARCHAR,
    CONTENT VARCHAR,
    LAST_UPDATED TIMESTAMP
);
