-- Demand Optimization: External Stage & Data Loading
USE SCHEMA MANUFACTURING_DEMAND.RAW;

CREATE OR REPLACE STAGE DEMAND_S3_STAGE
    URL = 's3://sg-manufacturing-demos-2026/demand/'
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

COPY INTO PRODUCTS FROM @DEMAND_S3_STAGE/products/;
COPY INTO WAREHOUSES FROM @DEMAND_S3_STAGE/warehouses/;
COPY INTO DEMAND_HISTORY FROM @DEMAND_S3_STAGE/demand_history/;
COPY INTO INVENTORY FROM @DEMAND_S3_STAGE/inventory/;
COPY INTO PURCHASE_ORDERS FROM @DEMAND_S3_STAGE/purchase_orders/;
COPY INTO PLANNING_DOCS FROM @DEMAND_S3_STAGE/planning_docs/;
