-- Apply Pareto product unit-sales skew on DEMAND_HISTORY.
-- Top 5% are volume drivers (10x), bottom 30% near-dead (0.15x).

USE SCHEMA MANUFACTURING_DEMAND.RAW;

CREATE OR REPLACE TABLE DEMAND_HISTORY AS
WITH ranked AS (
  SELECT PRODUCT_ID, ROW_NUMBER() OVER (ORDER BY ABS(HASH(PRODUCT_ID,'rk'))) AS rk FROM PRODUCTS
), tiered AS (
  SELECT PRODUCT_ID,
    CASE WHEN rk <= 25  THEN 10.0
         WHEN rk <= 75  THEN 4.0
         WHEN rk <= 175 THEN 1.8
         WHEN rk <= 350 THEN 0.6
         ELSE 0.15
    END AS volume_mult
  FROM ranked
)
SELECT d.PRODUCT_ID, d.WAREHOUSE_ID, d.DEMAND_DATE,
  GREATEST(1, ROUND(d.UNITS_SOLD * t.volume_mult * (50 + ABS(HASH(d.PRODUCT_ID, d.WAREHOUSE_ID, d.DEMAND_DATE,'qj'))%101)/100.0))::NUMBER AS UNITS_SOLD,
  GREATEST(1, ROUND(d.UNITS_FORECAST * t.volume_mult * (50 + ABS(HASH(d.PRODUCT_ID, d.WAREHOUSE_ID, d.DEMAND_DATE,'fj'))%101)/100.0))::NUMBER AS UNITS_FORECAST,
  d.FORECAST_ERROR
FROM DEMAND_HISTORY d JOIN tiered t ON d.PRODUCT_ID = t.PRODUCT_ID;
