-- Demand Optimization: Dynamic Tables
USE SCHEMA MANUFACTURING_DEMAND.CURATED;

CREATE OR REPLACE DYNAMIC TABLE FORECAST_ACCURACY
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.CATEGORY,
    DATE_TRUNC('week', d.DEMAND_DATE) AS WEEK,
    AVG(1 - ABS(d.FORECAST_ERROR)) * 100 AS AVG_ACCURACY_PCT,
    AVG(d.FORECAST_ERROR) * 100 AS BIAS_PCT,
    SUM(CASE WHEN d.FORECAST_DEMAND > d.ACTUAL_DEMAND THEN 1 ELSE 0 END) AS OVER_FORECAST_COUNT,
    SUM(CASE WHEN d.FORECAST_DEMAND < d.ACTUAL_DEMAND THEN 1 ELSE 0 END) AS UNDER_FORECAST_COUNT
FROM RAW.DEMAND_HISTORY d
JOIN RAW.PRODUCTS p ON d.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.CATEGORY, WEEK;

CREATE OR REPLACE DYNAMIC TABLE INVENTORY_HEALTH
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    w.WAREHOUSE_NAME,
    i.DAYS_OF_SUPPLY,
    i.VALUE_AT_RISK,
    i.ON_HAND_QTY,
    CASE
        WHEN i.DAYS_OF_SUPPLY > 35 THEN 'OVERSTOCK'
        WHEN i.DAYS_OF_SUPPLY < 7 THEN 'CRITICAL_LOW'
        WHEN i.DAYS_OF_SUPPLY < 14 THEN 'LOW'
        ELSE 'HEALTHY'
    END AS RISK_LEVEL
FROM RAW.INVENTORY i
JOIN RAW.PRODUCTS p ON i.PRODUCT_ID = p.PRODUCT_ID
JOIN RAW.WAREHOUSES w ON i.WAREHOUSE_ID = w.WAREHOUSE_ID
WHERE i.SNAPSHOT_DATE = (SELECT MAX(SNAPSHOT_DATE) FROM RAW.INVENTORY);

CREATE OR REPLACE DYNAMIC TABLE DEMAND_SIGNALS
    TARGET_LAG = '1 minute'
    WAREHOUSE = CORTEX
AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    AVG(CASE WHEN d.DEMAND_DATE >= DATEADD('day', -7, CURRENT_DATE()) THEN d.ACTUAL_DEMAND END) AS AVG_DEMAND_7D,
    AVG(CASE WHEN d.DEMAND_DATE >= DATEADD('day', -30, CURRENT_DATE()) THEN d.ACTUAL_DEMAND END) AS AVG_DEMAND_30D,
    (AVG_DEMAND_7D - AVG_DEMAND_30D) / NULLIF(AVG_DEMAND_30D, 0) * 100 AS GROWTH_RATE_PCT,
    RANK() OVER (PARTITION BY p.CATEGORY ORDER BY AVG_DEMAND_7D DESC) AS VELOCITY_RANK
FROM RAW.DEMAND_HISTORY d
JOIN RAW.PRODUCTS p ON d.PRODUCT_ID = p.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY;
