-- Demand Optimization: ML Models
USE SCHEMA MANUFACTURING_DEMAND.ML;

CREATE OR REPLACE VIEW FORECAST_INPUT AS
SELECT
    DATE_TRUNC('day', d.DEMAND_DATE) AS DS,
    p.CATEGORY || ' - ' || w.WAREHOUSE_NAME AS SERIES,
    SUM(d.ACTUAL_DEMAND) AS Y
FROM RAW.DEMAND_HISTORY d
JOIN RAW.PRODUCTS p ON d.PRODUCT_ID = p.PRODUCT_ID
JOIN RAW.WAREHOUSES w ON d.WAREHOUSE_ID = w.WAREHOUSE_ID
GROUP BY DS, SERIES;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST DEMAND_FORECAST_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'FORECAST_INPUT'),
    SERIES_COLNAME => 'SERIES',
    TIMESTAMP_COLNAME => 'DS',
    TARGET_COLNAME => 'Y'
);

-- Generate 14-day forecast
CALL DEMAND_FORECAST_MODEL!FORECAST(
    FORECASTING_PERIODS => 14,
    CONFIG_OBJECT => {'prediction_interval': 0.95}
);
